services:
  django:
    container_name: "django"
    hostname: "django"
    build:
      dockerfile: "./docker/django/Dockerfile"
    expose:
      - "80"
    volumes:
      - "./sec_transfer/media/:/sec_transfer/sec_transfer/media/"
    env_file:
      - "./.env"
    depends_on:
      - "postgresql"
    restart: "unless-stopped"

  nginx:
    container_name: "nginx"
    hostname: "nginx"
    build: 
      dockerfile: "./docker/nginx/Dockerfile"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./sec_transfer/media/:/var/www/media/"
    depends_on:
      - "django"
    restart: "unless-stopped"

  postgresql:
    container_name: "postgresql"
    hostname: "$POSTGRES_HOST"
    image: "postgres:latest"
    expose:
      - "$POSTGRES_PORT"
    volumes:
      - "./database/:/var/lib/postgresql/data"
    env_file:
      - "./.env"
    shm_size: "1gb"
    restart: "unless-stopped"
