# Generated by Django 5.2.1 on 2025-05-15 15:29

import django.db.models.deletion
import storage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to=storage.models.File._upload_to,
                        verbose_name='file',
                    ),
                ),
                (
                    'encrypted_key',
                    models.CharField(
                        help_text='Max length 32',
                        max_length=32,
                        verbose_name='encrypted key',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='updated at'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        related_query_name='files',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
