# Generated by Django 5.2.1 on 2025-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='gcm_tag',
            field=models.BinaryField(
                blank=True, max_length=16, verbose_name='AES gcm'
            ),
        ),
        migrations.AddField(
            model_name='file',
            name='iv',
            field=models.BinaryField(
                blank=True, max_length=12, verbose_name='AES iv'
            ),
        ),
    ]
