# Generated by Django 5.2.1 on 2025-05-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_file_gcm_tag_file_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='gcm_tag',
            field=models.BinaryField(max_length=16, verbose_name='AES gcm'),
        ),
        migrations.AlterField(
            model_name='file',
            name='iv',
            field=models.BinaryField(max_length=12, verbose_name='AES iv'),
        ),
    ]
