# Generated by Django 5.2.1 on 2025-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_file_gcm_tag_alter_file_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='encrypted_key',
            field=models.BinaryField(
                editable=True, max_length=32, verbose_name='AES encrypted key'
            ),
        ),
        migrations.AlterField(
            model_name='file',
            name='gcm_tag',
            field=models.BinaryField(
                editable=True, max_length=16, verbose_name='AES gcm'
            ),
        ),
        migrations.AlterField(
            model_name='file',
            name='iv',
            field=models.BinaryField(
                editable=True, max_length=12, verbose_name='AES iv'
            ),
        ),
    ]
