# Generated by Django 5.2.1 on 2025-05-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'storage',
            '0004_alter_file_encrypted_key_alter_file_gcm_tag_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='encrypted_key',
            field=models.CharField(
                max_length=256, verbose_name='AES encrypted key'
            ),
        ),
        migrations.AlterField(
            model_name='file',
            name='gcm_tag',
            field=models.CharField(max_length=16, verbose_name='AES gcm'),
        ),
        migrations.AlterField(
            model_name='file',
            name='iv',
            field=models.CharField(max_length=12, verbose_name='AES iv'),
        ),
    ]
